services:
  postgres:                         # Catalog DB for DuckLake metadata
    image: postgres:16
    container_name: dl-postgres
    environment: # Option A where client runs on postgres container: expose Postgres to the host at localhost:5432
      POSTGRES_USER: duck           #username
      POSTGRES_PASSWORD: duckpass   #password
      POSTGRES_DB: postgres
    ports: # Option B where client is running on a different container
      - "5432:5432"                 # expose to host (macbook) so that other containers other than postgres one can access it
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U duck -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  minio:                            # S3-compatible object storage
    image: minio/minio:latest
    container_name: dl-minio
    environment:
      MINIO_ROOT_USER: minioadmin            #username
      MINIO_ROOT_PASSWORD: "adminadmin"      #password
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"                 # for S3 API
      - "9001:9001"                 # for Web console
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  default: {}